### ISSUE TITLE
Prevent scalastyle-config.xml from being included in build artifact

### ISSUE THREAD

**Issue by patrickgalbreath** [ramencloud/sbt-config#30]
sbt-config is putting the generated scalastyle-config.xml file into the builds' `resource_managed/` directories, meaning that the file will be delivered any build artifact.  Since the file would only be needed at build time and not runtime we should find another home for it.  Putting it under `project/` would be a good fit.

**Comment by dot-vlad** [comment]
Putting into the /project will mean that it should be gitignored, so people don't commit it.

**Comment by ericdotdata** [comment]
Added in https://github.com/ramencloud/sbt-config/commit/9a984e305add1026bf334a90cd5aab02049606b1#diff-bf0116b11452dd8fb7779888f127e0f11399b20e4b551ce9b1b756c2f5fbccdfR342-R343
