### ISSUE TITLE
Check if generated resources would have different contents

### ISSUE THREAD

**Issue by patrickgalbreath** [ramencloud/sbt-config#38]
Some resources are generated as part of the build, most notably the scalafmt config file.

Originally the file would be recreated on each build, but this led to instability due to concurrent builds (possibly an extension of using ProjectRef and RootProject).  Subsequently the code was updated so that the file is only written if it doesn't exist, but this leaves the possibility of having outdated configuration if the generated file contents are updated.

This is a proposal to add a new check to see if the existing file would match the generated file.  This could be done, for example, by checking the MD5 hash of the latest config vs the existing file to see if it should be replaced.  Pseudocode:
```scala
 // presumably using java.security.MessageDigest with the MD5 algorithm
private def calculateMd5(reader: Reader): Array[Byte] = ???

private def scalafmtConfStream(): InputStream = getClass.getClassLoader.getResourceAsStream("scalafmt.conf")

lazy val scalafmtConfigMd5 = Using.Manager { manage => 
  val stream = manage(scalafmtConfStream())
  val reader = manage(new InputStreamReader(stream))
  calculateMd5(reader)
}

//...

if (!formatConfFile.exists || IO.read(formatConfFile)(calculateMd5) != scalafmtConfigMd5) {
  // existing code
}
```

**Comment by ericdotdata** [comment]
This was done in https://github.com/ramencloud/sbt-config/commit/3c1914a775802a721dd0681f546bc415133ab05f

**Comment by ericdotdata** [comment]
Well md5 wasn't done, but since you have to update the sbt-config plugin to update the styles, and a clean does it, I don't think the complete feature is needed.
